# Generated by Django 2.2.5 on 2019-09-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUB_TYPE_ID', models.CharField(max_length=20)),
                ('DISPOSE_UNIT_NAME', models.CharField(max_length=20)),
                ('DISPOSE_UNIT_ID', models.CharField(max_length=20)),
                ('EVENT_SRC_NAME', models.CharField(max_length=20)),
                ('EVENT_SRC_ID', models.CharField(max_length=20)),
                ('OPERATE_NUM', models.CharField(max_length=20)),
                ('OVERTIME_ARCHIVE_NUM', models.CharField(max_length=20)),
                ('INTIME_TO_ARCHIVE_NUM', models.CharField(max_length=20)),
                ('INTIME_ARCHIVE_NUM', models.CharField(max_length=20)),
                ('EVENT_PROPERTY_ID', models.CharField(max_length=20)),
                ('EVENT_PROPERTY_NAME', models.CharField(max_length=20)),
                ('OCCUR_PLACE', models.CharField(max_length=20)),
            ],
        ),
    ]
