# Generated by Django 2.2.5 on 2019-09-20 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='COMMUNITY_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='COMMUNITY_NAME',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='CREATE_TIME',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='CREATE_TIME'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='DISTRICT_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='DISTRICT_NAME',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='EVENT_TYPE_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='EVENT_TYPE_NAME',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='MAIN_TYPE_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='MAIN_TYPE_NAME',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='REC_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='REPORT_NUM',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='STREET_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='STREET_NAME',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='SUB_TYPE_NAME',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='DISPOSE_UNIT_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='DISPOSE_UNIT_NAME',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='EVENT_PROPERTY_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='EVENT_PROPERTY_NAME',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='EVENT_SRC_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='EVENT_SRC_NAME',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='INTIME_ARCHIVE_NUM',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='INTIME_TO_ARCHIVE_NUM',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='OCCUR_PLACE',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='OPERATE_NUM',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='OVERTIME_ARCHIVE_NUM',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='SUB_TYPE_ID',
            field=models.CharField(default='', max_length=20),
        ),
    ]
