# Generated by Django 2.2.5 on 2019-09-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20190920_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='sadness', max_length=20)),
                ('password', models.CharField(default='happiness', max_length=20)),
            ],
        ),
    ]
