# Generated by Django 2.2.5 on 2019-11-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='COMMUNITY_ID',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='DISPOSE_UNIT_ID',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='DISTRICT_ID',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='EVENT_PROPERTY_ID',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='EVENT_SRC_ID',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='EVENT_TYPE_ID',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='MAIN_TYPE_ID',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='REC_ID',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='STREET_ID',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='SUB_TYPE_ID',
            field=models.IntegerField(default='-1'),
        ),
    ]
