# Generated by Django 2.2.5 on 2019-11-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_auto_20191107_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='COMMUNITY_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='DISPOSE_UNIT_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='DISTRICT_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='EVENT_PROPERTY_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='EVENT_SRC_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='EVENT_TYPE_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='MAIN_TYPE_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='STREET_ID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='SUB_TYPE_ID',
            field=models.CharField(default='', max_length=20),
        ),
    ]
